# Generated by Django 5.1.4 on 2025-02-09 08:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email')),
                ('first_name', models.CharField(default='Anonymous', max_length=200)),
                ('last_name', models.CharField(blank=True, max_length=200, null=True)),
                ('tc', models.BooleanField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile_img', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('street_address', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=25, null=True, verbose_name='Phone Number')),
                ('city', models.CharField(blank=True, max_length=25, null=True)),
                ('zipcode', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('category_image', models.ImageField(null=True, upload_to='photos/categories')),
            ],
        ),
        migrations.CreateModel(
            name='Wholesaler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('company_name', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True, unique=True, verbose_name='Email')),
                ('license_number', models.CharField(max_length=50)),
                ('license_image', models.ImageField(blank=True, null=True, upload_to='wholesaler_licenses/')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('street_address', models.CharField(blank=True, max_length=255, null=True)),
                ('mobile_number1', models.CharField(blank=True, max_length=25, null=True, verbose_name='Mobile Number1')),
                ('mobile_number2', models.CharField(blank=True, max_length=25, null=True, verbose_name='Mobile Number2')),
                ('mobile_number3', models.CharField(blank=True, max_length=25, null=True, verbose_name='Mobile Number3')),
                ('zipcode', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('is_wholesaler', models.BooleanField(default=True)),
                ('product_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.productcategory')),
            ],
            options={
                'verbose_name': 'Wholesaler',
                'verbose_name_plural': 'Wholesalers',
            },
        ),
    ]
