# Generated by Django 5.1.4 on 2025-03-11 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_remove_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='name_ar',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='name_en',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
