# Generated by Django 5.1.4 on 2025-03-24 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_productcategory_name_ar_productcategory_name_en'),
        ('wholesaler', '0008_alter_product_wholesaler_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='tc',
        ),
        migrations.AddField(
            model_name='user',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='license_image',
            field=models.ImageField(blank=True, null=True, upload_to='wholesaler_licenses/'),
        ),
        migrations.AddField(
            model_name='user',
            name='license_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='mobile_number1',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Mobile Number 1'),
        ),
        migrations.AddField(
            model_name='user',
            name='mobile_number2',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Mobile Number 2'),
        ),
        migrations.AddField(
            model_name='user',
            name='mobile_number3',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Mobile Number 3'),
        ),
        migrations.AddField(
            model_name='user',
            name='product_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.productcategory'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('customer', 'Customer'), ('wholesaler', 'Wholesaler')], default='customer', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, default='Anonymous', max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Wholesaler',
        ),
    ]
