# Generated by Django 5.1.4 on 2025-06-24 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_user_is_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('customer', 'Customer'), ('wholesaler', 'Wholesaler'), ('admin', 'Admin')], default='customer', max_length=20),
        ),
    ]
