# Generated by Django 5.1.4 on 2025-03-29 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0001_initial'),
        ('wholesaler', '0008_alter_product_wholesaler_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='product',
        ),
        migrations.AddField(
            model_name='campaign',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='wholesaler.productvariant'),
        ),
    ]
