# Generated by Django 5.1.4 on 2025-02-09 08:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('actual_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('stock', models.IntegerField(blank=True, null=True)),
                ('is_in_campaign', models.BooleanField(default=False)),
                ('is_available', models.BooleanField(default=True)),
                ('campaign_discount_percentage', models.DecimalField(decimal_places=2, default=0.0, help_text='Enter discount as a percentage (e.g., 20 for 20%)', max_digits=5)),
                ('minimum_order_quantity_for_offer', models.PositiveIntegerField(default=1)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.productcategory')),
                ('wholesaler', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='authentication.wholesaler')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(default='')),
                ('public_id', models.CharField(default=0, max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='wholesaler.product')),
            ],
        ),
        migrations.CreateModel(
            name='WholesalerBankDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beneficiary_name', models.CharField(max_length=255)),
                ('bank_name', models.CharField(max_length=255)),
                ('bank_address', models.TextField()),
                ('account_number_iban', models.CharField(max_length=50, verbose_name='Account No/IBAN')),
                ('swift_code', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('wholesaler', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_details', to='authentication.wholesaler')),
            ],
            options={
                'verbose_name': 'Wholesaler Bank Detail',
                'verbose_name_plural': 'Wholesaler Bank Details',
            },
        ),
    ]
