# Generated by Django 5.1.4 on 2025-03-11 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholesaler', '0002_product_description_ar_product_description_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wholesalerbankdetails',
            name='bank_address_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='wholesalerbankdetails',
            name='bank_address_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='wholesalerbankdetails',
            name='bank_name_ar',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='wholesalerbankdetails',
            name='bank_name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='wholesalerbankdetails',
            name='beneficiary_name_ar',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='wholesalerbankdetails',
            name='beneficiary_name_en',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
