# Generated by Django 5.1.4 on 2025-03-15 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholesaler', '0003_wholesalerbankdetails_bank_address_ar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
