# Generated by Django 5.1.4 on 2025-03-16 09:33

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_productcategory_name_ar_productcategory_name_en'),
        ('wholesaler', '0004_product_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='actual_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='campaign_discount_percentage',
        ),
        migrations.RemoveField(
            model_name='product',
            name='minimum_order_quantity_for_offer',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='product',
            name='unit',
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(blank=True, help_text='Enter brand name', max_length=100, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='Weight in kg', max_digits=5, null=True)),
                ('liter', models.DecimalField(blank=True, decimal_places=2, help_text='Volume in liters', max_digits=5, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField(blank=True, null=True)),
                ('campaign_discount_percentage', models.DecimalField(decimal_places=2, default=0.0, help_text='Enter discount as a percentage (e.g., 20 for 20%)', max_digits=5)),
                ('minimum_order_quantity_for_offer', models.PositiveIntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='wholesaler.product')),
                ('wholesaler', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.wholesaler')),
            ],
        ),
        migrations.CreateModel(
            name='ProductVariantImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('public_id', models.CharField(default='', max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='wholesaler.product')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_images', to='wholesaler.productvariant')),
                ('wholesaler', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.wholesaler')),
            ],
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
