# Generated by Django 5.1.4 on 2025-03-16 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholesaler', '0005_remove_product_actual_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariantimage',
            name='image',
        ),
        migrations.AddField(
            model_name='productvariantimage',
            name='image_url',
            field=models.URLField(default=''),
        ),
    ]
