# Generated by Django 5.1.4 on 2025-03-18 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholesaler', '0006_remove_productvariantimage_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariantimage',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='wholesaler.product'),
        ),
    ]
