# Generated by Django 5.1.4 on 2025-03-24 07:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholesaler', '0007_alter_productvariantimage_product'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='wholesaler',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'wholesaler'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='wholesaler',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'wholesaler'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_variants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='productvariantimage',
            name='wholesaler',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'wholesaler'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_variant_images', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='wholesalerbankdetails',
            name='wholesaler',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_details', to=settings.AUTH_USER_MODEL),
        ),
    ]
