# Generated by Django 5.1.4 on 2025-03-29 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholesaler', '0008_alter_product_wholesaler_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='is_in_campaign',
            field=models.BooleanField(default=False),
        ),
    ]
