# Generated by Django 5.1.4 on 2025-06-25 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholesaler', '0009_productvariant_is_available_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
