# Generated by Django 5.1.4 on 2025-06-26 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholesaler', '0010_product_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productvariantimage',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
