# Generated by Django 5.1.4 on 2025-06-28 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholesaler', '0011_productvariant_is_default_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='campaign_discount_percentage',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='campaign_discount_admin',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Admin discount as a percentage (e.g., 20 for 20%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='campaign_discount_wholesaler',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Wholesaler discount as a percentage (e.g., 10 for 10%)', max_digits=5),
        ),
    ]
