# Generated by Django 5.1.4 on 2025-06-28 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholesaler', '0013_alter_productvariant_campaign_discount_admin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='minimum_order_quantity_for_offer',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='minimum_order_quantity_for_offer_by_admin',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='minimum_order_quantity_for_offer_by_wholesaler',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
