# Generated by Django 5.1.4 on 2025-06-28 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholesaler', '0014_remove_productvariant_minimum_order_quantity_for_offer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='minimum_order_quantity_for_offer_by_admin',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='minimum_order_quantity_for_offer_by_wholesaler',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
    ]
