# Generated by Django 5.1.4 on 2025-03-15 06:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_members', models.IntegerField()),
                ('members_more_than_15', models.IntegerField()),
                ('members_less_than_15', models.IntegerField()),
                ('members_more_than_60', models.IntegerField()),
                ('members_less_than_5', models.IntegerField()),
                ('meals_per_day', models.IntegerField()),
                ('eating_out_frequency', models.IntegerField()),
                ('dietary_preferences', models.TextField()),
                ('total_monthly_expense', models.FloatField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenseData', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
