# Generated by Django 5.1.4 on 2025-04-02 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_remove_order_product_order_variant'),
        ('wholesaler', '0009_productvariant_is_available_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignorder',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaign_orders', to='wholesaler.productvariant'),
        ),
    ]
