# Generated by Django 5.1.4 on 2025-06-29 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_remove_order_is_paid_remove_order_payment_status_and_more'),
        ('wholesaler', '0015_alter_productvariant_minimum_order_quantity_for_offer_by_admin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaignorder',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='campaignorder',
            name='total_price',
        ),
        migrations.RemoveField(
            model_name='campaignorder',
            name='variant',
        ),
        migrations.AlterField(
            model_name='campaignorder',
            name='remaining_balance',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='CampaignOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order.campaignorder')),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wholesaler.productvariant')),
            ],
        ),
    ]
