# Generated by Django 5.1.4 on 2025-06-29 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_remove_campaignorder_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignorder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
